name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - unittest
  push:
    branches:
      - main
      - unittest
      - 'releases/*'


jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}